#!/bin/bash

# CipherNest Setup Script for Linux
# This script automates the setup process for the CipherNest project

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    local missing_deps=()
    
    if ! command_exists node; then
        missing_deps+=("node")
    else
        NODE_VERSION=$(node --version | cut -d'v' -f2 | cut -d'.' -f1)
        if [ "$NODE_VERSION" -lt 18 ]; then
            log_warning "Node.js version is $NODE_VERSION, but version 18+ is recommended"
        fi
    fi
    
    if ! command_exists pnpm; then
        missing_deps+=("pnpm")
    fi
    
    if ! command_exists rustc; then
        missing_deps+=("rust")
    fi
    
    if ! command_exists dfx; then
        missing_deps+=("dfx")
    fi
    
    if [ ${#missing_deps[@]} -ne 0 ]; then
        log_error "Missing dependencies: ${missing_deps[*]}"
        log_info "Please install missing dependencies using the README guide"
        exit 1
    fi
    
    log_success "All prerequisites are installed"
}

# Start DFX replica
start_replica() {
    log_info "Starting Internet Computer local replica..."
    
    # Check if DFX is already running
    if dfx ping >/dev/null 2>&1; then
        log_warning "DFX replica is already running"
        return 0
    fi
    
    # Start DFX in background
    dfx start --background
    
    # Wait for replica to be ready
    log_info "Waiting for replica to start..."
    local timeout=30
    local count=0
    
    while ! dfx ping >/dev/null 2>&1; do
        if [ $count -ge $timeout ]; then
            log_error "Timeout waiting for DFX replica to start"
            exit 1
        fi
        sleep 1
        ((count++))
    done
    
    log_success "DFX replica is running"
}

# Deploy backend canister
deploy_backend() {
    log_info "Deploying chat backend canister..."
    
    # Build and deploy the canister
    dfx deploy chat_backend
    
    # Get canister ID
    CANISTER_ID=$(dfx canister id chat_backend)
    log_success "Backend canister deployed with ID: $CANISTER_ID"
    
    # Export for use in frontend setup
    export BACKEND_CANISTER_ID="$CANISTER_ID"
}

# Setup frontend
setup_frontend() {
    log_info "Setting up frontend..."
    
    # Navigate to frontend directory
    cd src/chat_frontend
    
    # Install dependencies
    log_info "Installing frontend dependencies..."
    pnpm install
    
    # Create environment file
    log_info "Creating environment configuration..."
    cat > .env.local << EOF
# CipherNest Frontend Environment Variables
# Generated by setup script on $(date)

NEXT_PUBLIC_CHAT_BACKEND_CANISTER_ID=$BACKEND_CANISTER_ID
NODE_ENV=development
NEXT_PUBLIC_IC_HOST=http://localhost:4943
EOF
    
    log_success "Frontend setup completed"
    
    # Return to project root
    cd ../..
}

# Start frontend development server
start_frontend() {
    log_info "Starting frontend development server..."
    
    cd src/chat_frontend
    
    # Start in background and capture PID
    pnpm dev &
    FRONTEND_PID=$!
    
    # Wait a moment for server to start
    sleep 3
    
    # Check if server started successfully
    if kill -0 $FRONTEND_PID 2>/dev/null; then
        log_success "Frontend server started (PID: $FRONTEND_PID)"
        echo $FRONTEND_PID > .frontend.pid
    else
        log_error "Failed to start frontend server"
        exit 1
    fi
    
    cd ../..
}

# Display status and next steps
show_status() {
    log_success "🎉 CipherNest setup completed successfully!"
    echo
    echo "📋 Project Status:"
    echo "  ✅ DFX replica: Running"
    echo "  ✅ Backend canister: Deployed ($BACKEND_CANISTER_ID)"
    echo "  ✅ Frontend server: Running on http://localhost:3000"
    echo
    echo "🚀 Next Steps:"
    echo "  1. Open your browser and navigate to: http://localhost:3000"
    echo "  2. The app will automatically generate cryptographic keys"
    echo "  3. Click 'Open Chats' to start messaging"
    echo "  4. Test the post-quantum encryption features"
    echo
    echo "🛠️  Development Commands:"
    echo "  • View backend logs: dfx canister logs chat_backend"
    echo "  • Stop DFX replica: dfx stop"
    echo "  • Restart frontend: cd src/chat_frontend && pnpm dev"
    echo
    echo "📚 For more information, see the README.md file"
}

# Cleanup function
cleanup() {
    log_info "Cleaning up..."
    
    # Kill frontend server if it's running
    if [ -f "src/chat_frontend/.frontend.pid" ]; then
        FRONTEND_PID=$(cat src/chat_frontend/.frontend.pid)
        if kill -0 $FRONTEND_PID 2>/dev/null; then
            kill $FRONTEND_PID
            log_info "Frontend server stopped"
        fi
        rm -f src/chat_frontend/.frontend.pid
    fi
}

# Handle script interruption
trap cleanup EXIT INT TERM

# Main setup function
main() {
    echo "🔐 CipherNest Setup Script"
    echo "=========================="
    echo
    
    # Check if we're in the right directory
    if [ ! -f "dfx.json" ]; then
        log_error "Please run this script from the CipherNest project root directory"
        exit 1
    fi
    
    # Run setup steps
    check_prerequisites
    start_replica
    deploy_backend
    setup_frontend
    start_frontend
    show_status
    
    # Keep script running to maintain frontend server
    log_info "Press Ctrl+C to stop all services and exit"
    while true; do
        sleep 1
    done
}

# Parse command line arguments
case "${1:-}" in
    --help|-h)
        echo "CipherNest Setup Script"
        echo
        echo "Usage: $0 [OPTIONS]"
        echo
        echo "Options:"
        echo "  --help, -h     Show this help message"
        echo "  --clean        Clean setup (reset DFX state)"
        echo
        echo "This script will:"
        echo "  1. Check prerequisites"
        echo "  2. Start DFX replica"
        echo "  3. Deploy backend canister"
        echo "  4. Setup frontend environment"
        echo "  5. Start development server"
        exit 0
        ;;
    --clean)
        log_info "Performing clean setup..."
        dfx stop 2>/dev/null || true
        dfx start --clean --background
        ;;
esac

# Run main setup
main
